### ISSUE TITLE
Version 1.9.96 Roadmap

### ISSUE THREAD

**Issue by ilyaskarim** [Uconnect-Technologies/wertik-js#227]
### Version 1.9.96 Roadmap

- [x] Allow extending options for Socket.IO.
- [x] Allow support for pg-native.
- [x] Add an option that will users choose to send an email or not on User signup.
- [x] Searching for Mongo the same as Mysql.
- [x] Setup Auth helper. Initial helpers, validatePassword.
- [x] Fix relationships Issue when using MongoDB.
- [x] Retire MongoDB From app.
### Development

- [x] Add database details as .env
